#讀入CSV檔

In [33]:
import pandas as pd

df = pd.read_csv('tzdata15.csv') #讀入csv檔
temp=df[['欄位名稱','數值']] #只顯示所需欄位
type=temp.groupby(['欄位名稱'])['數值'].sum().reset_index() #欄位名稱欄中，將相同支出項目(如設備費、業務費)之金額加總
type['year']=2015 #新增年份欄位
print(type)

df16 = pd.read_csv('tzdata16.csv')
temp16=df[['欄位名稱','數值']]
type16=temp16.groupby(['欄位名稱'])['數值'].sum().reset_index()
type16['year']=2016
print(type16)

df17 = pd.read_csv('tzdata17.csv')
temp17=df[['欄位名稱','數值']]
type17=temp17.groupby(['欄位名稱'])['數值'].sum().reset_index()
type17['year']=2017
print(type17)

df18 = pd.read_csv('tzdata18.csv')
temp18=df[['欄位名稱','數值']]
type18=temp18.groupby(['欄位名稱'])['數值'].sum().reset_index()
type18['year']=2018
print(type18)

frames=[type,type16,type17,type18]
result=pd.concat(frames)
print(result)

           欄位名稱        數值  year
0            國立   8864971  2015
1       國立_償還借款         0  2015
2   國立_折舊、折耗及攤銷    947209  2015
3       國立_經常支出   8578878  2015
4   國立_經常支出報廢金額         0  2015
5       國立_資本支出    402520  2015
6            市立   4436889  2015
7       市立_償還借款         0  2015
8   市立_折舊、折耗及攤銷         0  2015
9       市立_經常支出   4214019  2015
10  市立_經常支出報廢金額         0  2015
11      市立_資本支出    162244  2015
12           私立  14405198  2015
13      私立_償還借款    569998  2015
14  私立_折舊、折耗及攤銷         0  2015
15      私立_經常支出  11852395  2015
16  私立_經常支出報廢金額    534787  2015
17      私立_資本支出   4149311  2015
           欄位名稱        數值  year
0            國立   8864971  2016
1       國立_償還借款         0  2016
2   國立_折舊、折耗及攤銷    947209  2016
3       國立_經常支出   8578878  2016
4   國立_經常支出報廢金額         0  2016
5       國立_資本支出    402520  2016
6            市立   4436889  2016
7       市立_償還借款         0  2016
8   市立_折舊、折耗及攤銷         0  2016
9       市立_經常支出   4214019  2016
10  市立_經常支出報廢金額         0  2016
11      市立_資本支出    162244  2016
12           私立  14405198  2016
13      私立_償還借款    569998  2016
14  私立_折舊、折耗及攤銷         0  2016
15      私立_經常支出  11852395  2016
16  私立_經常支出報廢金額    534787  2016
17      私立_資本支出   4149311  2016
           欄位名稱        數值  year
0            國立   8864971  2017
1       國立_償還借款         0  2017
2   國立_折舊、折耗及攤銷    947209  2017
3       國立_經常支出   8578878  2017
4   國立_經常支出報廢金額         0  2017
5       國立_資本支出    402520  2017
6            市立   4436889  2017
7       市立_償還借款         0  2017
8   市立_折舊、折耗及攤銷         0  2017
9       市立_經常支出   4214019  2017
10  市立_經常支出報廢金額         0  2017
11      市立_資本支出    162244  2017
12           私立  14405198  2017
13      私立_償還借款    569998  2017
14  私立_折舊、折耗及攤銷         0  2017
15      私立_經常支出  11852395  2017
16  私立_經常支出報廢金額    534787  2017
17      私立_資本支出   4149311  2017
           欄位名稱        數值  year
0            國立   8864971  2018
1       國立_償還借款         0  2018
2   國立_折舊、折耗及攤銷    947209  2018
3       國立_經常支出   8578878  2018
4   國立_經常支出報廢金額         0  2018
5       國立_資本支出    402520  2018
6            市立   4436889  2018
7       市立_償還借款         0  2018
8   市立_折舊、折耗及攤銷         0  2018
9       市立_經常支出   4214019  2018
10  市立_經常支出報廢金額         0  2018
11      市立_資本支出    162244  2018
12           私立  14405198  2018
13      私立_償還借款    569998  2018
14  私立_折舊、折耗及攤銷         0  2018
15      私立_經常支出  11852395  2018
16  私立_經常支出報廢金額    534787  2018
17      私立_資本支出   4149311  2018
           欄位名稱        數值  year
0            國立   8864971  2015
1       國立_償還借款         0  2015
2   國立_折舊、折耗及攤銷    947209  2015
3       國立_經常支出   8578878  2015
4   國立_經常支出報廢金額         0  2015
..          ...       ...   ...
13      私立_償還借款    569998  2018
14  私立_折舊、折耗及攤銷         0  2018
15      私立_經常支出  11852395  2018
16  私立_經常支出報廢金額    534787  2018
17      私立_資本支出   4149311  2018

[72 rows x 3 columns]

In [34]:
result

           欄位名稱        數值  year
0            國立   8864971  2015
1       國立_償還借款         0  2015
2   國立_折舊、折耗及攤銷    947209  2015
3       國立_經常支出   8578878  2015
4   國立_經常支出報廢金額         0  2015
..          ...       ...   ...
13      私立_償還借款    569998  2018
14  私立_折舊、折耗及攤銷         0  2018
15      私立_經常支出  11852395  2018
16  私立_經常支出報廢金額    534787  2018
17      私立_資本支出   4149311  2018

[72 rows x 3 columns]